apiVersion: apps/v1
kind: Deployment
metadata:
  name: myboot
  labels:
    app: myboot
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myboot
  template:
    metadata:
      labels:
        app: myboot
    spec:
      containers:
      - name: myboot
        image: quay.io/rhdevelopers/myboot:v1
        ports:
        - containerPort: 8080

